// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAclw0OlOCSARHiiv9RwuxDcXX-dalmoVc',
    appId: '1:1059429077157:web:ea8503a6d949cbd3acfd4c',
    messagingSenderId: '1059429077157',
    projectId: 'eduworld-6ba8b',
    authDomain: 'eduworld-6ba8b.firebaseapp.com',
    storageBucket: 'eduworld-6ba8b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl0PVe6jNP438Ebw2O-nHAkOXGJ__2dFU',
    appId: '1:1059429077157:android:9d114ccaae5c87cdacfd4c',
    messagingSenderId: '1059429077157',
    projectId: 'eduworld-6ba8b',
    storageBucket: 'eduworld-6ba8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWV7TO0cbMPs7Ydmjr5t2S0YNJL4irz4M',
    appId: '1:1059429077157:ios:cddf19776d988e66acfd4c',
    messagingSenderId: '1059429077157',
    projectId: 'eduworld-6ba8b',
    storageBucket: 'eduworld-6ba8b.firebasestorage.app',
    iosBundleId: 'com.ragnie.eduworld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWV7TO0cbMPs7Ydmjr5t2S0YNJL4irz4M',
    appId: '1:1059429077157:ios:40f2cba6be9d13b1acfd4c',
    messagingSenderId: '1059429077157',
    projectId: 'eduworld-6ba8b',
    storageBucket: 'eduworld-6ba8b.firebasestorage.app',
    iosBundleId: 'com.example.eduWorld',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAclw0OlOCSARHiiv9RwuxDcXX-dalmoVc',
    appId: '1:1059429077157:web:ed422a71e82b2d2eacfd4c',
    messagingSenderId: '1059429077157',
    projectId: 'eduworld-6ba8b',
    authDomain: 'eduworld-6ba8b.firebaseapp.com',
    storageBucket: 'eduworld-6ba8b.firebasestorage.app',
  );

}